---
title: "00- Data Cleaning"
output:
  pdf_document: 
    fig_width: 20
    fig_height: 9
  html_document: 
    toc: true
    toc_float:
        collapsed: false
        smooth_scroll: true
    fig_width: 20
---

# Directory and doc rules

```{r, setup, eval=TRUE, include=TRUE}

knitr::opts_chunk$set(
  root.dir = here::here(),
  echo = TRUE,         # Display code chunks
  eval = TRUE,         # Evaluate code chunks
  warning = FALSE,     # Hide warnings
  message = FALSE,     # Hide messages
  #fig.width = 15,       # Set plot width in inches
  #fig.height = 9,      # Set plot height in inches
  fig.align = "center" # Align plots to the center
)

```

# Load Data

```{r, load data}

# double check where you are
# *NOTE* set to root (WDFWmussels) and not a directory within - check into why that is happening in the knitr block
getwd()

# load data
data<- read.csv("../data/full_bio_morph_with_geo_grouping.csv")


```

---
## Data Format
P450 & SOD Activity (Unit / mg"^"-1"~"protein)
Length, Height, Width, Shell Thickness - mm
Weight - g
CI - unitless
---

# Data Review

```{r review data}

# take a look at your df
str(data) # df setup review

# str() tells us that our df has 312 rows and 9 columns and that our sample_id and site number are being treated as integers; this might be a problem in analyses and plotting.

summary(data) # df stats for each column

# summary() tells us a few useful things: (1) our lat/ long bounds which we'll need for mapping, (2) we have NA values in p450 and condition_factor that need to be investigated before moving forward.

```

# Dealing with NA's
```{r }

# Fixing NAs or errant values

# replace 0's with NA
data$p450[data$p450 <= 0] <- NA

# replace any values below LOQ with imputed LOQ
data$sod[data$sod <= 0] <- 0.0025

# check
summary(data)

write.csv(data, "/Users/cmantegna/Documents/GitHub/WDFWmussels/data/full_with_na.csv")

```

# Column Names - Don't Run

```{r}

# i also noticed that all of my column names aren't lowercase, so let's fix that to prevent unnecessary mistakes
colnames(data) <- tolower(colnames(data))

```

# Normality

```{r}

# distribution normality or non-normality our analysis path, let's check
# test assumes normality, so any p-value > .05 indicates a rejection of that assumption

shapiro.test(data$p450) # NOT normal
shapiro.test(data$sod) # NOT normal
shapiro.test(data$ci1) # NOT normal
shapiro.test(data$ci2) # NOT normal
shapiro.test(data$ci3) # NOT normal
shapiro.test(data$shell) # Normal

```

# Plot - P450

```{r}

# taking a look before anything else is best practice - so let's
# by sample ID
plot(data$sample_id, data$p450, 
     xlab = "Sample", ylab = "P450 Value", 
     main = "P450 Activity by Sample ID",
     pch = 16, col = "blue")

# by site
boxplot(data$p450 ~ factor(data$site_name), 
        xlab = "Site", ylab = "P450 Value", 
        main = "P450 Activity by Site",
        col = "blue")

# looks like we have a team of outliers to address

```

# Plot - SOD

```{r}

# taking a look before anything else is best practice - so let's
# by sample ID
plot(data$sample_id, data$sod, 
     xlab = "Sample", ylab = "SOD Value", 
     main = "SOD Activity by Sample ID",
     pch = 16, col = "blue")

# by site
boxplot(data$sod ~ factor(data$site_name), 
        xlab = "Site", ylab = "SOD Value", 
        main = "SOD Activity by Site",
        col = "blue")

# looks like we have a few outliers to deal with

```

# Plot - CI1

```{r}

# taking a look before anything else is best practice - so let's
# by sample ID
plot(data$sample_id, data$ci1, 
     xlab = "Sample", ylab = "Condition Facotr", 
     main = "Condition Factor by Sample ID",
     pch = 16, col = "blue")

# by site
boxplot(data$ci1 ~ factor(data$site_name), 
        xlab = "Site", ylab = "Condition Factor", 
        main = "Condition Factor by Site",
        col = "blue")

```

# Plot - CI2

```{r}

# taking a look before anything else is best practice - so let's
# by sample ID
plot(data$sample_id, data$ci2, 
     xlab = "Sample", ylab = "Condition Facotr", 
     main = "Condition Factor by Sample ID",
     pch = 16, col = "blue")

# by site
boxplot(data$ci2 ~ factor(data$site_name), 
        xlab = "Site", ylab = "Condition Factor", 
        main = "Condition Factor by Site",
        col = "blue")

```

# Plot - CI3
```{r}

# taking a look before anything else is best practice - so let's
# by sample ID
plot(data$sample_id, data$ci3, 
     xlab = "Sample", ylab = "Condition Facotr", 
     main = "Condition Factor by Sample ID",
     pch = 16, col = "blue")

# by site
boxplot(data$ci3 ~ factor(data$site_name), 
        xlab = "Site", ylab = "Condition Factor", 
        main = "Condition Factor by Site",
        col = "blue")

```

# Plot - Shell_Thickness
```{r}

# taking a look before anything else is best practice - so let's
# by sample ID
plot(data$sample_id, data$shell, 
     xlab = "Sample", ylab = "Shell Thickness", 
     main = "Shell Thickness by Sample ID",
     pch = 16, col = "blue")

# by site
boxplot(data$shell ~ factor(data$site_name), 
        xlab = "Site", ylab = "Shell Thickness", 
        main = "Shell Thickness by Site",
        col = "blue")

# outliers are not clear here

```

# Check for Outliers - No Need
```{r}

# let's find the outliers for each metric we are reviewing (p450, sod, condition_factor and avg_thickness). ChatGPT helped create the loop.
metrics <- c("p450", "sod", "condition_factor", "avg_thickness")  # identify columns of interest

# Loop through each metric and compute outliers
for (marker in metrics) {
  Q1 <- quantile(data[[marker]], 0.25, na.rm = TRUE)
  Q3 <- quantile(data[[marker]], 0.75, na.rm = TRUE)
  IQR_value <- Q3 - Q1
  
  lower_bound <- Q1 - 1.5 * IQR_value
  upper_bound <- Q3 + 1.5 * IQR_value
  
  # Create a new column to flag outliers for each metric
  data[[paste0(marker, "_outlier")]] <- ifelse(data[[marker]] < lower_bound | data[[marker]] > upper_bound, TRUE, FALSE)
}

# View a summary of outliers
summary(data[, paste0(metrics, "_outlier")]) # outliers: p450= 8, sod= 19, cf= 10, at= 3 

# write out this df for further use
# *NOTE* check why it only saves with the full path and not the relative

# last saved on 2.6.25
#write.csv(data, file = "/Users/cmantegna/Documents/GitHub/WDFWmussels/data/cleaned/all_cleaned.csv", row.names = FALSE)

```
