---
  title: "011- p450 Site, Reporting Area and PAH grouping"
output:
  html_document: 
  toc: true
toc_float:
  collapsed: false
smooth_scroll: true
fig_width: 20
pdf_document: 
  fig_width: 20
fig_height: 9
---
  
# Directory and doc rules

```{r, setup, eval=TRUE, include=TRUE}

knitr::opts_chunk$set(
  echo = TRUE,         # Display code chunks
  eval = TRUE,         # Evaluate code chunks
  warning = FALSE,     # Hide warnings
  message = FALSE,     # Hide messages
  fig.width = 20,       # Set plot width in inches
  fig.height = 9,      # Set plot height in inches
  fig.align = "center" )# Align plots to the center

```

# Load packages

```{r}

library(tinytex)
library(tidyr)
library(tidyverse)
library(vegan)

```

# Load data

```{r}

#getwd()
apdata<- read.csv("/Users/cmantegna/Documents/WDFWmussels/data/p450_analytes.csv")

```

# Boxplot
## Site name

```{r}
#p450 is in activity/ mg protein

pplot<- ggplot(apdata, aes(x = site_name, y = p450)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 14),  
    axis.text.y = element_text(size = 14) 
  )

print(pplot)
#ggsave(plot=pplot, filename="/Users/cmantegna/Documents/WDFWmussels/output/figures/p450boxplotSITE.png", width=20, height=9)
```

## Ranked (lowest to highest) by site name
```{r}

#order the sites by value

data_ordered <- apdata[order(apdata$p450),]

#create a factor 
data_ordered$site_name <- factor(data_ordered$site_name, levels = unique(data_ordered$site_name))

#plot with ordered site names
ranked<- ggplot(data_ordered, aes(x = site_name, y = p450)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) # Rotate x labels if needed

print(ranked)

#ggsave(plot=ranked, filename="/Users/cmantegna/Documents/WDFWmussels/output/figures/p450boxplotSITEranked.png", width=20, height=9)
```

## Reporting area
```{r}

apdata$reporting_area <- as.character(apdata$reporting_area)

#p450
pplot<- ggplot(apdata, aes(x = reporting_area, y = p450)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) 

print(pplot)
#ggsave(plot=pplot, filename="/Users/cmantegna/Documents/WDFWmussels/output/figures/p450boxplotRA.png", width=20, height=9)

```

## PAH group 3 
```{r}
apdata$PAHgroup3 <- as.character(apdata$PAHgroup3)

pplot<- ggplot(apdata, aes(x = PAHgroup3, y = p450)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) 

print(pplot)
#ggsave(plot=pplot, filename="/Users/cmantegna/Documents/WDFWmussels/output/figures/p450boxplotGROUP3.png", width=20, height=9)

```

## PAH group 4 
```{r}
apdata$PAHgroup4 <- as.character(apdata$PAHgroup4)

pplot<- ggplot(apdata, aes(x = PAHgroup4, y = p450)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) 

print(pplot)
#ggsave(plot=pplot, filename="/Users/cmantegna/Documents/WDFWmussels/output/figures/p450boxplotGROUP4.png", width=20, height=9)

```

## PAH group 5 
```{r}
apdata$PAHgroup5 <- as.character(apdata$PAHgroup5)

pplot<- ggplot(apdata, aes(x = PAHgroup5, y = p450)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) 

print(pplot)
#ggsave(plot=pplot, filename="/Users/cmantegna/Documents/WDFWmussels/output/figures/p450boxplotGROUP5.png", width=20, height=9)

```

## PAH group 6 
```{r}
apdata$PAHgroup6 <- as.character(apdata$PAHgroup6)

pplot<- ggplot(apdata, aes(x = PAHgroup6, y = p450)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) 

print(pplot)
#ggsave(plot=pplot, filename="/Users/cmantegna/Documents/WDFWmussels/output/figures/p450boxplotGROUP6.png", width=20, height=9)

```
