---
title: "Significant p450 results"
---

# Directory and doc rules

```{r, setup, eval=TRUE, include=TRUE}

knitr::opts_chunk$set(
  echo = TRUE,         # Display code chunks
  eval = TRUE,         # Evaluate code chunks
  warning = FALSE,     # Hide warnings
  message = FALSE,     # Hide messages
  fig.width = 20,       # Set plot width in inches
  fig.height = 9,      # Set plot height in inches
  fig.align = "center" # Align plots to the center
)

```

# Load packages

```{r}
library(tinytex)
library(tidyr)
library(tidyverse)
library(vegan)

```

# Load data

```{r}

#getwd()
data<- read.csv("/Users/cmantegna/Documents/WDFWmussels/data/p450data.csv")
indv<- read.csv("/Users/cmantegna/Documents/WDFWmussels/data/avgP450_analytes.csv")
summed<- read.csv("/Users/cmantegna/Documents/WDFWmussels/data/avgP450_analytes2.csv")
metal <- read.csv("/Users/cmantegna/Documents/WDFWmussels/data/avgP450_metals.csv")
```

# reporting areas
```{r}

library(ggplot2)
library(dplyr)


# reporting areas
reporting_areas <- c(8.2, 10, 11, 12, 13)
filtered_data_reporting_areas <- data %>% filter(reporting_area %in% reporting_areas)

# Box plot- reporting area
ggplot(filtered_data_reporting_areas, aes(x = factor(reporting_area), y = p450)) +
  geom_boxplot() +
  labs(x = 'Reporting Area', y = 'p450 Value', title = 'p450 Values by Reporting Area') +
  theme_minimal()

```

# PAHgroup7
```{r}
# PAH group 7

# Filter for PAH group 7
filtered_data_pah_group7 <- data %>% filter(PAHgroup7 > 0)

# Create a single box plot for PAH group 7
ggplot(filtered_data_pah_group7, aes(x = factor(PAHgroup7), y = p450)) +
  geom_boxplot() +
  labs(x = 'PAH Group 7 ID', y = 'p450 Value', title = 'p450 Values for PAH Group 7') +
  theme_minimal()


```
# PAHgroup8
```{r}
# PAH group 8

# Filter for PAH group 8
filtered_data_pah_group8 <- data %>% filter(PAHgroup7 > 0)

# Create a single box plot for PAH group 8
ggplot(filtered_data_pah_group8, aes(x = factor(PAHgroup8), y = p450)) +
  geom_boxplot() +
  labs(x = 'PAH Group 8 ID', y = 'p450 Value', title = 'p450 Values for PAH Group 8') +
  theme_minimal()

```