---
title: "02- Analysis Groups: Adding the Groupings for Analysis by Site, Reporting Area, PCB Group, Geographic Area and PAH Groups"
output:
  pdf_document: 
    fig_width: 20
    fig_height: 9
  html_document: 
    toc: true
    toc_float:
        collapsed: false
        smooth_scroll: true
    fig_width: 20
---

# Directory and doc rules

```{r, setup, eval=TRUE, include=TRUE}

# libraries
library(knitr)
library(tidyr)
library(dplyr)
library(vegan)
library(pgirmess)
library(ggplot2)

# global options
knitr::opts_chunk$set(
  root.dir = here::here(),
  echo = TRUE,         # Display code chunks
  eval = TRUE,         # Evaluate code chunks
  warning = FALSE,     # Hide warnings
  message = FALSE,     # Hide messages
  #fig.width = 15,       # Set plot width in inches
  #fig.height = 9,      # Set plot height in inches
  fig.align = "center" # Align plots to the center
)

```

# Load & Check Data
```{r}

# double check where you are
# *NOTE* see 00-data_cleaned for directory issue
getwd()

# load data
# complete df
data<- read.csv("../data/cleaned/complete_with_groups.csv")
p16<- read.csv("../data/cleaned/p16_grouping_for_averages.csv")
p42<- read.csv("../data/cleaned/p42_grouping_for_averages.csv")
phmw<- read.csv("../data/cleaned/phmw_grouping_for_averages.csv")
plmw<- read.csv("../data/cleaned/plmw_grouping_for_averages.csv")
pcb<- read.csv("../data/cleaned/pcb_grouping_for_averages.csv")
# check it out
#str(data) # checking df structure
# note that sample_id and site_number are integers and may need to be adjusted to characters for analysis

#summary(data) #checking df contents

#colnames(data) <- tolower(colnames(data))

```

# All groups created. Do not run lines 66 - 124 unless rebuilding the df
## Adding PAH + PCB groups, 5 groups in total
```{r}

library(classInt)
library(dplyr)

# Extract the DryValue column
dry_values <- phmw$DryValue

# Compute Fisher-Jenks breaks for 6 groups
num_classes <- 6
breaks <- classIntervals(dry_values, num_classes, style = "fisher")$brks

# Print the breakpoints
print(breaks)

# Create group assignments based on the breaks
phmw$DryValue_Group <- cut(dry_values, breaks = breaks, labels = 1:num_classes, include.lowest = TRUE)

# Check the first few rows with the new grouping
head(phmw)


# write out new table

write.csv(phmw, "../data/phmw_group.csv", row.names = FALSE)

```

## Geographic (lat/ long) (n=6)
```{r}

# make geographic clusters based on lat/ long coordinates in 5 groups since it looks like there are 5 distinct areas of sites

# use k-means clustering 
set.seed(123)
clusters <- kmeans(data[, c("latitude", "longitude")], centers = 5)
data <- data %>%
  mutate(geo = as.factor(clusters$cluster))

# lat/long ranges for each group
latlong_ranges <- data %>%
  group_by(geo) %>%
  summarize(
    lat_range = paste0(round(min(latitude), 2), " - ", round(max(latitude), 2)),
    long_range = paste0(round(min(longitude), 2), " - ", round(max(longitude), 2))
  ) %>%
  mutate(label = paste0("Group ", geo, "\nLat: ", lat_range, "\nLong: ", long_range))

# add lat/long ranges back to the df
data <- data %>%
  left_join(latlong_ranges, by = "geo")

write.csv(data, "../data/cleaned/updated_geo_grouping", row.names = FALSE)

```

# Adding chem groups to data
```{r}

# just replace the df name in the parenthesis to add all of the chem groups
library(tidyr)
library(dplyr)

df <- df %>%
  left_join(plmw, by = "site_name")

# check
head(df)

write.csv(df, "/Users/cmantegna/Documents/GitHub/WDFWmussels/data/all_chem_join.csv")
```

