---
title: "021- SOD Site, Reporting Area and PAH grouping"
output:
  html_document: 
    toc: true
    toc_float:
        collapsed: false
        smooth_scroll: true
    fig_width: 20
  pdf_document: 
    fig_width: 20
    fig_height: 9
---

# Directory and doc rules

```{r, setup, eval=TRUE, include=TRUE}

knitr::opts_chunk$set(
  echo = TRUE,         # Display code chunks
  eval = TRUE,         # Evaluate code chunks
  warning = FALSE,     # Hide warnings
  message = FALSE,     # Hide messages
  fig.width = 20,       # Set plot width in inches
  fig.height = 9,      # Set plot height in inches
  fig.align = "center" # Align plots to the center
)

```

# Load packages

```{r}
library(tinytex)
library(tidyr)
library(tidyverse)
library(vegan)

```

# Load data

```{r}

#getwd()
#sdata<- read.csv("/Users/cmantegna/Documents/WDFWmussels/data/soddata.csv")
asdata<- read.csv("/Users/cmantegna/Documents/WDFWmussels/data/sod_analytes.csv")

```

```{r}

# Data contains numbers below 0 that must be adjusted.These numbers represent samples whose values were below the limit of quantification using the SOD kit. There was some activity in the raw sample, but it is too far below the limit of the standard curve to be accurately quantified.


#replace any SOD values at or below 0 with half of the lower detection limit of .005 (.005*.5). Lower detection limit determined by assay protocol by the manufacturer, Cayman.
asdata$sod[asdata$sod <= 0] <- 0.0025

```

# Boxplots
## Site name

```{r}

#sod is in units/ mg protein
pplot<- ggplot(asdata, aes(x = site_name, y = sod)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 14),  
    axis.text.y = element_text(size = 14) 
  )

print(pplot)
#ggsave(plot=pplot, filename="/Users/cmantegna/Documents/WDFWmussels/output/figures/sodboxplotSITE.png", width=20, height=9)
```

## Ranked (lowest to highest) by site name
```{r}

#order the sites by value
data_ordered <- asdata[order(asdata$sod),]

#create a factor 
data_ordered$site_name <- factor(data_ordered$site_name, levels = unique(data_ordered$site_name))

#plot with ordered site names
ranked<- ggplot(data_ordered, aes(x = site_name, y = sod)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) # Rotate x labels if needed

print(ranked)

#ggsave(plot=ranked, filename="/Users/cmantegna/Documents/WDFWmussels/output/figures/sodboxplotSITEranked.png", width=20, height=9)
```

## Reporting area
```{r}

asdata$reporting_area <- as.character(asdata$reporting_area)

pplot<- ggplot(asdata, aes(x = reporting_area, y = sod)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) 

print(pplot)
#ggsave(plot=pplot, filename="/Users/cmantegna/Documents/WDFWmussels/output/figures/sodboxplotRA.png", width=20, height=9)

```

## PAH group 3 
```{r}
asdata$PAHgroup3 <- as.character(asdata$PAHgroup3)

pplot<- ggplot(asdata, aes(x = PAHgroup3, y = sod)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) 

print(pplot)
#ggsave(plot=pplot, filename="/Users/cmantegna/Documents/WDFWmussels/output/figures/sodboxplotGROUP3.png", width=20, height=9)

```

## PAH group 4 
```{r}
asdata$PAHgroup4 <- as.character(asdata$PAHgroup4)

pplot<- ggplot(asdata, aes(x = PAHgroup4, y = sod)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) 

print(pplot)
#ggsave(plot=pplot, filename="/Users/cmantegna/Documents/WDFWmussels/output/figures/sodboxplotGROUP4.png", width=20, height=9)

```

## PAH group 5 
```{r}
asdata$PAHgroup5 <- as.character(asdata$PAHgroup5)

pplot<- ggplot(asdata, aes(x = PAHgroup5, y = sod)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) 

print(pplot)
#ggsave(plot=pplot, filename="/Users/cmantegna/Documents/WDFWmussels/output/figures/sodboxplotGROUP5.png", width=20, height=9)

```

## PAH group 6 
```{r}
asdata$PAHgroup6 <- as.character(asdata$PAHgroup6)

pplot<- ggplot(asdata, aes(x = PAHgroup6, y = sod)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) 

print(pplot)
#ggsave(plot=pplot, filename="/Users/cmantegna/Documents/WDFWmussels/output/figures/sodboxplotGROUP6.png", width=20, height=9)

```
