---
title: "01- Visual Data Exploration"
---

# Directory and doc rules

```{r, setup, include=FALSE}

knitr::opts_knit$set(root.dir = '/code')

```

# Load packages

```{r}
#install.packages(c("ggplot2", "sf", "viridis", "rnaturalearth", "rnaturalearthdata"))
library(tidyr)
#library(tidyverse)
#library(ggplot2)
library(vegan)
library(sf)
library(viridis)
library(rnaturalearth)
library(rnaturalearthdata)


```

# Load data

```{r}

getwd()
#data has all sites, coordinates, p450, sod, condition factor, economic factor data
data<- read.csv("/Users/cmantegna/Documents/WDFWmussels/data/biomarkerfull.csv")

```
```{r}

as.numeric("weight_initial", "weight_change", "length", "width", "height", "condition_factor", "economic_index")

```

# 0's and negative number management

SOD values that are negative are changed to 0 signifying that the value was undetectable.\
p450 values that are 0 are missing, not actual 0's.

```{r}

#get rid of the p450 values that are 0
data <- data[data$p450 != 0, ]

#change any negative numbers to 0 to indicate not detectable
data$SOD <- ifelse(data$SOD <= 0, 0, data$SOD)

```

```{r}
world <- ne_states(country = "united states of america", returnclass = "sf")
washington_map <- world[world$name == "Washington", ]
1
```
```{r}

library(ggplot2)
ggplot() + 
  geom_sf(data = washington_map, fill = "lightgrey", color = "white") +
  geom_point(data = data, aes(x = lon, y = lat, color = p450), size = 3) +
  scale_color_viridis(option = "C", name = "p450") +
  theme_minimal() +
  labs(title = "Washington State - p450 Data")

```

