---
title: "031- Morphometrics Site, Reporting Area and PAH grouping"
output:
  html_document: 
    toc: true
    toc_float:
        collapsed: false
        smooth_scroll: true
    fig_width: 20
  pdf_document: 
    fig_width: 20
    fig_height: 9
---

# Directory and doc rules

```{r, setup, eval=TRUE, include=TRUE}

knitr::opts_chunk$set(
  echo = TRUE,         # Display code chunks
  eval = TRUE,         # Evaluate code chunks
  warning = FALSE,     # Hide warnings
  message = FALSE,     # Hide messages
  fig.width = 20,       # Set plot width in inches
  fig.height = 9,      # Set plot height in inches
  fig.align = "center" # Align plots to the center
)

```

# Load packages

```{r}
library(tinytex)
library(tidyr)
library(tidyverse)
library(vegan)

```

# Load data

```{r}

#getwd()
mdata<- read.csv("/Users/cmantegna/Documents/WDFWmussels/data/morphometricdata.csv")

```

# Boxplots - cf
## Site name

```{r}

mplot<- ggplot(mdata, aes(x = site_name, y = cf)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) 

print(mplot)
#ggsave(plot=mplot, filename="/Users/cmantegna/Documents/WDFWmussels/output/figures/CFboxplotSITE.png", width=20, height=9)

```

## Ranked (lowest to highest) by site name
```{r}

#order the sites by value

data_ordered <- mdata[order(mdata$cf),]

#create a factor 
data_ordered$site_name <- factor(data_ordered$site_name, levels = unique(data_ordered$site_name))

#plot with ordered site names
ranked<- ggplot(data_ordered, aes(x = site_name, y = cf)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) # Rotate x labels if needed

print(ranked)
#ggsave(plot=ranked, filename="/Users/cmantegna/Documents/WDFWmussels/output/figures/CFboxplotSITEranked.png", width=20, height=9)
```

## Reporting area
```{r}

mdata$reporting_area <- as.character(mdata$reporting_area)

mplot<- ggplot(mdata, aes(x = reporting_area, y = cf)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) 

print(mplot)
#ggsave(plot=mplot, filename="/Users/cmantegna/Documents/WDFWmussels/output/figures/CFboxplotRA.png", width=20, height=9)

```

## PAH group 3 
```{r}

mdata$PAHgroup3 <- as.character(mdata$PAHgroup3)

pplot<- ggplot(mdata, aes(x = PAHgroup3, y = cf)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) 

print(pplot)
#ggsave(plot=pplot, filename="/Users/cmantegna/Documents/WDFWmussels/output/figures/CFboxplotGROUP3.png", width=20, height=9)

```

## PAH group 4 
```{r}

mdata$PAHgroup4 <- as.character(mdata$PAHgroup4)

pplot<- ggplot(mdata, aes(x = PAHgroup4, y = cf)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) 

print(pplot)
#ggsave(plot=pplot, filename="/Users/cmantegna/Documents/WDFWmussels/output/figures/CFboxplotGROUP4.png", width=20, height=9)

```

## PAH group 5 
```{r}

mdata$PAHgroup5 <- as.character(mdata$PAHgroup5)

pplot<- ggplot(mdata, aes(x = PAHgroup5, y = cf)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) 

print(pplot)
#ggsave(plot=pplot, filename="/Users/cmantegna/Documents/WDFWmussels/output/figures/CFboxplotGROUP5.png", width=20, height=9)

```

## PAH group 6 
```{r}

mdata$PAHgroup6 <- as.character(mdata$PAHgroup6)

pplot<- ggplot(mdata, aes(x = PAHgroup6, y = cf)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) 

print(pplot)
#ggsave(plot=pplot, filename="/Users/cmantegna/Documents/WDFWmussels/output/figures/CFboxplotGROUP6.png", width=20, height=9)

```


# Box plots - at
## Site name

```{r}

mplot<- ggplot(mdata, aes(x = site_name, y = at)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) 

print(mplot)
#ggsave(plot=mplot, filename="/Users/cmantegna/Documents/WDFWmussels/output/figures/ATboxplotSITE.png", width=20, height=9)
```

## Ranked (lowest to highest) by site name
```{r}

#order the sites by value

data_ordered <- mdata[order(mdata$at),]

#create a factor with the ordered site names
data_ordered$site_name <- factor(data_ordered$site_name, levels = unique(data_ordered$site_name))

#plot with ordered site names
ranked<- ggplot(data_ordered, aes(x = site_name, y = at)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) # Rotate x labels if needed

print(ranked)
#ggsave(plot=ranked, filename="/Users/cmantegna/Documents/WDFWmussels/output/figures/ATboxplotSITEranked.png", width=20, height=9)
```

## Reporting area
```{r}

mdata$reporting_area <- as.character(mdata$reporting_area)


mplot<- ggplot(mdata, aes(x = reporting_area, y = at)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) 

print(mplot)
#ggsave(plot=mplot, filename="/Users/cmantegna/Documents/WDFWmussels/output/figures/ATboxplotRA.png", width=20, height=9)

```

## PAH group 3 
```{r}

mdata$PAHgroup3 <- as.character(mdata$PAHgroup3)

pplot<- ggplot(mdata, aes(x = PAHgroup3, y = at)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) 

print(pplot)
#ggsave(plot=pplot, filename="/Users/cmantegna/Documents/WDFWmussels/output/figures/ATboxplotGROUP3.png", width=20, height=9)

```

## PAH group 4 
```{r}

mdata$PAHgroup4 <- as.character(mdata$PAHgroup4)

pplot<- ggplot(mdata, aes(x = PAHgroup3, y = at)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) 

print(pplot)
#ggsave(plot=pplot, filename="/Users/cmantegna/Documents/WDFWmussels/output/figures/ATboxplotGROUP4.png", width=20, height=9)

```

## PAH group 5 
```{r}

mdata$PAHgroup5 <- as.character(mdata$PAHgroup5)

pplot<- ggplot(mdata, aes(x = PAHgroup5, y = at)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) 

print(pplot)
#ggsave(plot=pplot, filename="/Users/cmantegna/Documents/WDFWmussels/output/figures/ATboxplotGROUP5.png", width=20, height=9)

```

## PAH group 6 
```{r}

mdata$PAHgroup6 <- as.character(mdata$PAHgroup6)

pplot<- ggplot(mdata, aes(x = PAHgroup6, y = at)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) 

print(pplot)
#ggsave(plot=pplot, filename="/Users/cmantegna/Documents/WDFWmussels/output/figures/ATboxplotGROUP6.png", width=20, height=9)

```
