---
title: "04- Pairwise Comparisons, PERMANOVA, KW + Dunn Post Hoc"
output:
  pdf_document: 
    fig_width: 20
    fig_height: 9
  html_document: 
    toc: true
    toc_float:
        collapsed: false
        smooth_scroll: true
    fig_width: 20
---

# Directory and doc rules

```{r, setup, eval=TRUE, include=TRUE}

# libraries
library(knitr)
library(tidyr)
library(dplyr)
library(vegan)
library(pgirmess)
library(ggplot2)

# global options
knitr::opts_chunk$set(
  root.dir = here::here(),
  echo = TRUE,         # Display code chunks
  eval = TRUE,         # Evaluate code chunks
  warning = FALSE,     # Hide warnings
  message = FALSE,     # Hide messages
  #fig.width = 15,       # Set plot width in inches
  #fig.height = 9,      # Set plot height in inches
  fig.align = "center" # Align plots to the center
)

```

# Load & Check Data
```{r}

# double check where you are
# *NOTE* see 00-data_cleaned for directory issue
getwd()

# ALL individual samples
data<- read.csv("../data/cleaned/all_samples_all_groups.csv")
pdata<- read.csv("../data/cleaned/p450_samples_all_groups.csv")
# Averaged
adata<- read.csv("../data/cleaned/avg_samples_all_groups.csv")
# check it out
#str(data) # checking df structure

#summary(data) #checking df contents

#colnames(data) <- tolower(colnames(data)) # if needed

```

# making groups characters
```{r}
# make analysis groups a factor (reporting area, geographic group, pcb group, site, pah group)
# change to a factor - all data
data$site_name <- as.character(data$site_name)
data$reporting_area <- as.factor(data$reporting_area)
data$km4 <- as.factor(data$km4)
data$km5 <- as.factor(data$km5)
data$hc4 <- as.factor(data$hc4)
data$hc5 <- as.factor(data$hc5)
data$p16 <- as.factor(data$p16)
data$p42 <- as.factor(data$p42)
data$plmw <- as.factor(data$plmw)
data$phmw <- as.factor(data$phmw)
data$pcb <- as.factor(data$pcb)

#p450 data
pdata$site_name <- as.character(pdata$site_name)
pdata$reporting_area <- as.factor(pdata$reporting_area)
pdata$km4 <- as.factor(pdata$km4)
pdata$km5 <- as.factor(pdata$km5)
pdata$hc4 <- as.factor(pdata$hc4)
pdata$hc5 <- as.factor(pdata$hc5)
pdata$p16 <- as.factor(pdata$p16)
pdata$p42 <- as.factor(pdata$p42)
pdata$plmw <- as.factor(pdata$plmw)
pdata$phmw <- as.factor(pdata$phmw)
pdata$pcb <- as.factor(pdata$pcb)

```

# KW & Post Hoc (individual metrics for each group)
## p450
### All to post hoc except p16, p42, plmw
```{r}

kruskal.test(p450 ~ site_name, data = pdata) # p= 6.442e-6
kruskal.test(p450 ~ reporting_area, data = pdata) # p= 0.0001749
kruskal.test(p450 ~ km4, data = pdata) # p= 0.001926
kruskal.test(p450 ~ km5, data = pdata) # p= 0.007549
kruskal.test(p450 ~ hc4, data = pdata) # p= 0.03691
kruskal.test(p450 ~ hc5, data = pdata) # p= 0.02398
kruskal.test(p450 ~ p16, data = pdata)  # p= 0.07492
kruskal.test(p450 ~ p42, data = pdata) # p= 0.6623
kruskal.test(p450 ~ plmw, data = pdata) # p= 0.2345
kruskal.test(p450 ~ phmw, data = pdata) # p= 0.01149
kruskal.test(p450 ~ pcb, data = pdata) # p= 0.006962

```

```{r}

mc_site<- as.data.frame(kruskalmc(p450 ~ site_name, data = pdata, method = "bonferroni"))
mc_reporting<- as.data.frame(kruskalmc(p450 ~ reporting_area, data = pdata, method = "bonferroni")) 
mc_km4<- as.data.frame(kruskalmc(p450 ~ km4, data = pdata, method = "bonferroni"))
mc_km5<- as.data.frame(kruskalmc(p450 ~ km5, data = pdata, method = "bonferroni"))
mc_hc4<- as.data.frame(kruskalmc(p450 ~ hc4, data = pdata, method = "bonferroni"))
mc_hc5<- as.data.frame(kruskalmc(p450 ~ hc5, data = pdata, method = "bonferroni"))
mc_phmw<- as.data.frame(kruskalmc(p450 ~ phmw, data = pdata, method = "bonferroni"))
mc_pcb<- as.data.frame(kruskalmc(p450 ~ pcb, data = pdata, method = "bonferroni"))


head(mc_site) #no
head(mc_reporting) #no
head(mc_km4) # 1-3, 3-4
head(mc_km5) #no
head(mc_hc4) #1-3
head(mc_hc5) #1-3
head(mc_phmw) #1-3
head(mc_pcb) #no

```

## sod
### Site and PCB group to posthoc
```{r}

kruskal.test(sod ~ site_name, data = data) # p= 0.001777
kruskal.test(sod ~ reporting_area, data = data) # p= 0.3136
kruskal.test(sod ~ km4, data = data) # p= 0.8714
kruskal.test(sod ~ km5, data = data) # p= 0.2262
kruskal.test(sod ~ hc4, data = data) # p= 0.7625
kruskal.test(sod ~ hc5, data = data) # p= 0.8258
kruskal.test(sod ~ p16, data = data)  # p= 0.4546
kruskal.test(sod ~ p42, data = data) # p= 0.1848
kruskal.test(sod ~ plmw, data = data) # p= 0.3703
kruskal.test(sod ~ phmw, data = data) # p= 0.2044
kruskal.test(sod ~ pcb, data = data) # p= 0.02254

```

```{r}

mc_site<- as.data.frame(kruskalmc(sod ~ site_name, data = data, method = "bonferroni"))
mc_pcb<- as.data.frame(kruskalmc(sod ~ pcb, data = data, method = "bonferroni"))

head(mc_site) #no
head(mc_pcb) #1-5

```

## ci1
### Site, hc5, p16, p42, plmw to posthoc
```{r}

kruskal.test(ci1 ~ site_name, data = data) # p= 4.216e-05
kruskal.test(ci1 ~ reporting_area, data = data) # p= 0.1622
kruskal.test(ci1 ~ km4, data = data) # p= 0.6122
kruskal.test(ci1 ~ km5, data = data) # p= 0.5029
kruskal.test(ci1 ~ hc4, data = data) # p= 0.6041
kruskal.test(ci1 ~ hc5, data = data) # p= 0.001344
kruskal.test(ci1 ~ p16, data = data)  # p= 0.003065
kruskal.test(ci1 ~ p42, data = data) # p= 0.02241
kruskal.test(ci1 ~ plmw, data = data) # p= 0.003599
kruskal.test(ci1 ~ phmw, data = data) # p= 0.06767
kruskal.test(ci1 ~ pcb, data = data) # p= 0.05673

```

```{r}

mc_site<- as.data.frame(kruskalmc(ci1 ~ site_name, data = data, method = "bonferroni"))
mc_hc5<- as.data.frame(kruskalmc(ci1 ~ hc5, data = data, method = "bonferroni"))
mc_p16<- as.data.frame(kruskalmc(ci1 ~ p16, data = data, method = "bonferroni"))
mc_p42<- as.data.frame(kruskalmc(ci1 ~ p42, data = data, method = "bonferroni"))
mc_plmw<- as.data.frame(kruskalmc(ci1 ~ plmw, data = data, method = "bonferroni"))

head(mc_site) #no
head(mc_hc5) #1-5
head(mc_p16) #no
head(mc_p42) #no
head(mc_plmw) #2-4

```

## ci2
### Site, km4, km5, hc4, hc5, p16, pcb to post hoc
```{r}

kruskal.test(ci2 ~ site_name, data = data) # p= 1.255e-08
kruskal.test(ci2 ~ reporting_area, data = data) # p= 0.2123
kruskal.test(ci2 ~ km4, data = data) # p= 0.04206
kruskal.test(ci2 ~ km5, data = data) # p= 0.02856
kruskal.test(ci2 ~ hc4, data = data) # p= 0.04803
kruskal.test(ci2 ~ hc5, data = data) # p= 0.02338
kruskal.test(ci2 ~ p16, data = data)  # p= 0.00433
kruskal.test(ci2 ~ p42, data = data) # p= 0.06513
kruskal.test(ci2 ~ plmw, data = data) # p= 0.6611
kruskal.test(ci2 ~ phmw, data = data) # p= 0.6535
kruskal.test(ci2 ~ pcb, data = data) # p= 0.00243

```

```{r}

mc_site<- as.data.frame(kruskalmc(ci2 ~ site_name, data = data, method = "bonferroni"))
mc_km4<- as.data.frame(kruskalmc(ci2 ~ km4, data = data, method = "bonferroni"))
mc_km5<- as.data.frame(kruskalmc(ci2 ~ km5, data = data, method = "bonferroni"))
mc_hc4<- as.data.frame(kruskalmc(ci2 ~ hc4, data = data, method = "bonferroni"))
mc_hc5<- as.data.frame(kruskalmc(ci2 ~ hc5, data = data, method = "bonferroni"))
mc_p16<- as.data.frame(kruskalmc(ci2 ~ p16, data = data, method = "bonferroni"))
mc_pcb<- as.data.frame(kruskalmc(ci2 ~ pcb, data = data, method = "bonferroni"))

head(mc_site) #no
head(mc_km4) #no
head(mc_km5) #no
head(mc_hc4) #no
head(mc_hc5) #no
head(mc_p16) #1-2
head(mc_pcb) #2-4

```

## ci3
### All but chems to post hoc
```{r}

kruskal.test(ci3 ~ site_name, data = data) # p= 1.673e-05
kruskal.test(ci3 ~ reporting_area, data = data) # p= 0.001512
kruskal.test(ci3 ~ km4, data = data) # p= 0.0003531
kruskal.test(ci3 ~ km5, data = data) # p= 0.0007519
kruskal.test(ci3 ~ hc4, data = data) # p= 0.0001921
kruskal.test(ci3 ~ hc5, data = data) # p= 1.089e-05
kruskal.test(ci3 ~ p16, data = data)  # p= 0.2789
kruskal.test(ci3 ~ p42, data = data) # p= 0.2736
kruskal.test(ci3 ~ plmw, data = data) # p= 0.4666
kruskal.test(ci3 ~ phmw, data = data) # p= 0.6491
kruskal.test(ci3 ~ pcb, data = data) # p= 0.07342

```

```{r}

mc_site<- as.data.frame(kruskalmc(ci3 ~ site_name, data = data, method = "bonferroni"))
mc_reporting<- as.data.frame(kruskalmc(ci3 ~ reporting_area, data = data, method = "bonferroni")) 
mc_km4<- as.data.frame(kruskalmc(ci3 ~ km4, data = data, method = "bonferroni"))
mc_km5<- as.data.frame(kruskalmc(ci3 ~ km5, data = data, method = "bonferroni"))
mc_hc4<- as.data.frame(kruskalmc(ci3 ~ hc4, data = data, method = "bonferroni"))
mc_hc5<- as.data.frame(kruskalmc(ci3 ~ hc5, data = data, method = "bonferroni"))

head(mc_site) #no
head(mc_reporting) #6-7, 6-8.2, 6,11
head(mc_km4) #1-3, 2-3, 3-4
head(mc_km5) #1-5
head(mc_hc4) #1-3, 2-3, 3-4
head(mc_hc5) #1-5

```

# ANOVA 
## shell thickness
### Significant result for site (p= 5.71e-16 ), RA (p= 1.09e-6), km4 (p= 1.34e-05), km5 (p= 9e-08), hc4 (p= 7.16e-05),  hc5 (p= 0.000103), p16 (p= 0.00016), p42 (p= 0.00527), phmw (p= 0.0194), pcb (p=1.8e-06)
```{r}

library(car)
library(multcomp)

# Define grouping variables
grouping_vars <- c("site_name", "reporting_area", "km4", "km5", "hc4", "hc5", "p16", "p42", "phmw", "plmw", "pcb")

# Function to run ANOVA and post hoc test
run_anova_posthoc <- function(group_var, data) {
  
  # Run ANOVA
  anova_model <- aov(shell ~ get(group_var), data = data)
  anova_summary <- summary(anova_model)

  # Extract p-value from ANOVA table
  p_value <- anova_summary[[1]]["Pr(>F)"][1,1]  

  # Only proceed if ANOVA is significant
  if (p_value < 0.05) {
    cat("\n### Significant ANOVA results for shell thickness by", group_var, "###\n")
    print(anova_summary)

    # Run Tukey's HSD post hoc test
    posthoc_result <- TukeyHSD(anova_model)

    # Convert to data frame for filtering
    posthoc_df <- as.data.frame(posthoc_result[[1]])
    posthoc_df <- cbind(comparison = rownames(posthoc_df), posthoc_df)  # Add comparison column

    # Filter only significant results (p < 0.05)
    significant_posthoc <- posthoc_df[posthoc_df$`p adj` < 0.05, , drop = FALSE]

    if (nrow(significant_posthoc) > 0) {
      cat("\n### Significant Tukey Post Hoc Comparisons for", group_var, "###\n")
      print(significant_posthoc)
    } else {
      cat("\n### No significant post hoc differences for", group_var, "###\n")
    }

    return(list(ANOVA = anova_summary, PostHoc = significant_posthoc))
  } else {
    cat("\n### No significant ANOVA differences for shell thickness by", group_var, "###\n")
    return(NULL)
  }
}

# Run ANOVA + post hoc for each grouping variable and store only significant results
anova_results <- lapply(grouping_vars, function(var) run_anova_posthoc(var, data))
names(anova_results) <- grouping_vars

# Remove NULL results (where ANOVA was not significant)
anova_results <- anova_results[!sapply(anova_results, is.null)]

```
