---
title: "05- WDFW Analytes Data for Coorelation with Biomarker Values"
output:
  html_document: 
    fig_width: 8
  pdf_document: 
    fig_width: 8
    fig_height: 5
---

### Directory and doc rules

```{r, setup, eval=TRUE, include=TRUE}

knitr::opts_chunk$set(
  echo = TRUE,         # Display code chunks
  eval = TRUE,         # Evaluate code chunks
  warning = FALSE,     # Hide warnings
  message = FALSE,     # Hide messages
  fig.width = 8,       # Set plot width in inches
  fig.height = 5,      # Set plot height in inches
  fig.align = "center" # Align plots to the center
)

```

# Load packages

```{r, eval= FALSE}

library(tidyr)
library(tidyverse)
library(ggplot2)
library(vegan)

```

# Load data

```{r}

getwd()
#data has all sites, coordinates, p450, sod, condition factor, economic factor data
data<- read.csv("/Users/cmantegna/Documents/WDFWmussels/data/biomarkerfull.csv")

#ana<- read.csv("/Users/cmantegna/Documents/Biomarker Data Analysis/PAHanalytes.csv")

```

### Review setup

```{r}

str(data)
str(ana)

```

```{r}
summary(data)
summary(ana)

```






