---
title: old stats from before the ibr was introduced
---

# Dunn's - none needed - lines

```{r}
# not significant
dunn_result <- dunnTest(sod ~ site_name, data = sample_data, method = "bh") 
dunn_df <- dunn_result$res %>%
  dplyr::select(Comparison, Z, P.unadj, P.adj) %>%
  tidyr::separate(Comparison, into = c("Group1", "Group2"), sep = " - ") %>%
  dplyr::mutate(Significant = ifelse(P.adj < 0.05, "Yes", "No"))
dunn_table <- dunn_df %>%
  dplyr::mutate(across(c(P.unadj, P.adj), round, digits = 4)) %>%
  dplyr::arrange(P.adj)
print(dunn_table) # view

```

## shell
```{r}

# site - significant
dunn_result <- dunnTest(shell ~ site_name, data = sample_data, method = "bh") 
dunn_df <- dunn_result$res %>%
  dplyr::select(Comparison, Z, P.unadj, P.adj) %>%
  tidyr::separate(Comparison, into = c("Group1", "Group2"), sep = " - ") %>%
  dplyr::mutate(Significant = ifelse(P.adj < 0.05, "Yes", "No"))
dunn_table <- dunn_df %>%
  dplyr::mutate(across(c(P.unadj, P.adj), round, digits = 4)) %>%
  dplyr::arrange(P.adj)
print(dunn_table) # view

groups <- unique(c(dunn_df$Group1, dunn_df$Group2)) # add letter designation
pval_matrix <- matrix(1, nrow = length(groups), ncol = length(groups),
                      dimnames = list(groups, groups))
for (i in 1:nrow(dunn_df)) {
  g1 <- dunn_df$Group1[i]
  g2 <- dunn_df$Group2[i]
  p <- dunn_df$P.adj[i]
  pval_matrix[g1, g2] <- p
  pval_matrix[g2, g1] <- p
}
cld_letters <- multcompLetters(pval_matrix < 0.05)$Letters
cld_df <- data.frame(
  Group = names(cld_letters),
  CLD = cld_letters,
  stringsAsFactors = FALSE
)
dunn_table_with_cld <- dunn_table %>%
  left_join(cld_df, by = c("Group1" = "Group")) %>%
  rename(Group1_CLD = CLD) %>%
  left_join(cld_df, by = c("Group2" = "Group")) %>%
  rename(Group2_CLD = CLD)

head(dunn_table_with_cld)
#write.csv(dunn_table_with_cld, "/Users/cmantegna/Documents/Github/WDFWmussels/output/dunn_shell_site.csv", row.names = FALSE) # write it out


# reporting area - significant
dunn_result <- dunnTest(shell ~ reporting_area, data = sample_data, method = "bh") 
dunn_df <- dunn_result$res %>%
  dplyr::select(Comparison, Z, P.unadj, P.adj) %>%
  tidyr::separate(Comparison, into = c("Group1", "Group2"), sep = " - ") %>%
  dplyr::mutate(Significant = ifelse(P.adj < 0.05, "Yes", "No"))

dunn_table <- dunn_df %>%
  dplyr::mutate(across(c(P.unadj, P.adj), round, digits = 4)) %>%
  dplyr::arrange(P.adj)

print(dunn_table) # view
groups <- unique(c(dunn_df$Group1, dunn_df$Group2)) # add letter designation
pval_matrix <- matrix(1, nrow = length(groups), ncol = length(groups),
                      dimnames = list(groups, groups))
for (i in 1:nrow(dunn_df)) {
  g1 <- dunn_df$Group1[i]
  g2 <- dunn_df$Group2[i]
  p <- dunn_df$P.adj[i]
  pval_matrix[g1, g2] <- p
  pval_matrix[g2, g1] <- p
}
cld_letters <- multcompLetters(pval_matrix < 0.05)$Letters
cld_df <- data.frame(
  Group = names(cld_letters),
  CLD = cld_letters,
  stringsAsFactors = FALSE
)
dunn_table_with_cld <- dunn_table %>%
  left_join(cld_df, by = c("Group1" = "Group")) %>%
  rename(Group1_CLD = CLD) %>%
  left_join(cld_df, by = c("Group2" = "Group")) %>%
  rename(Group2_CLD = CLD)

head(dunn_table_with_cld)
#write.csv(dunn_table_with_cld, "/Users/cmantegna/Documents/Github/WDFWmussels/output/dunn_shell_ra.csv", row.names = FALSE) # write it out

```

## ci1 - site
```{r}

# site - significant
dunn_result <- dunnTest(ci1 ~ site_name, data = sample_data, method = "bh") 
dunn_df <- dunn_result$res %>%
  dplyr::select(Comparison, Z, P.unadj, P.adj) %>%
  tidyr::separate(Comparison, into = c("Group1", "Group2"), sep = " - ") %>%
  dplyr::mutate(Significant = ifelse(P.adj < 0.05, "Yes", "No"))

dunn_table <- dunn_df %>%
  dplyr::mutate(across(c(P.unadj, P.adj), round, digits = 4)) %>%
  dplyr::arrange(P.adj)
print(dunn_table) # view

groups <- unique(c(dunn_df$Group1, dunn_df$Group2)) # add letter designation
pval_matrix <- matrix(1, nrow = length(groups), ncol = length(groups),
                      dimnames = list(groups, groups))
for (i in 1:nrow(dunn_df)) {
  g1 <- dunn_df$Group1[i]
  g2 <- dunn_df$Group2[i]
  p <- dunn_df$P.adj[i]
  pval_matrix[g1, g2] <- p
  pval_matrix[g2, g1] <- p
}
cld_letters <- multcompLetters(pval_matrix < 0.05)$Letters
cld_df <- data.frame(
  Group = names(cld_letters),
  CLD = cld_letters,
  stringsAsFactors = FALSE
)
dunn_table_with_cld <- dunn_table %>%
  left_join(cld_df, by = c("Group1" = "Group")) %>%
  rename(Group1_CLD = CLD) %>%
  left_join(cld_df, by = c("Group2" = "Group")) %>%
  rename(Group2_CLD = CLD)

head(dunn_table_with_cld)
#write.csv(dunn_table_with_cld, "/Users/cmantegna/Documents/Github/WDFWmussels/output/dunn_ci1_site.csv", row.names = FALSE) # write it out

```

## ci2 - site
```{r}

# site - not significant
dunn_result <- dunnTest(ci2 ~ site_name, data = sample_data, method = "bh") 
dunn_df <- dunn_result$res %>%
  dplyr::select(Comparison, Z, P.unadj, P.adj) %>%
  tidyr::separate(Comparison, into = c("Group1", "Group2"), sep = " - ") %>%
  dplyr::mutate(Significant = ifelse(P.adj < 0.05, "Yes", "No"))

dunn_table <- dunn_df %>%
  dplyr::mutate(across(c(P.unadj, P.adj), round, digits = 4)) %>%
  dplyr::arrange(P.adj)

print(dunn_table) # view

```

## ci3 - site & reporting area
```{r}

# site is not significant
dunn_result <- dunnTest(ci3 ~ site_name, data = sample_data, method = "bh") 
dunn_df <- dunn_result$res %>%
  dplyr::select(Comparison, Z, P.unadj, P.adj) %>%
  tidyr::separate(Comparison, into = c("Group1", "Group2"), sep = " - ") %>%
  dplyr::mutate(Significant = ifelse(P.adj < 0.05, "Yes", "No"))

dunn_table <- dunn_df %>%
  dplyr::mutate(across(c(P.unadj, P.adj), round, digits = 4)) %>%
  dplyr::arrange(P.adj)
print(dunn_table) # view

# reporting area is significant (2)
dunn_result <- dunnTest(ci3 ~ reporting_area, data = sample_data, method = "bh") 
dunn_df <- dunn_result$res %>%
  dplyr::select(Comparison, Z, P.unadj, P.adj) %>%
  tidyr::separate(Comparison, into = c("Group1", "Group2"), sep = " - ") %>%
  dplyr::mutate(Significant = ifelse(P.adj < 0.05, "Yes", "No"))
dunn_table <- dunn_df %>%
  dplyr::mutate(across(c(P.unadj, P.adj), round, digits = 4)) %>%
  dplyr::arrange(P.adj)
print(dunn_table) # view

groups <- unique(c(dunn_df$Group1, dunn_df$Group2)) # add letter designation
pval_matrix <- matrix(1, nrow = length(groups), ncol = length(groups),
                      dimnames = list(groups, groups))
for (i in 1:nrow(dunn_df)) {
  g1 <- dunn_df$Group1[i]
  g2 <- dunn_df$Group2[i]
  p <- dunn_df$P.adj[i]
  pval_matrix[g1, g2] <- p
  pval_matrix[g2, g1] <- p
}

cld_letters <- multcompLetters(pval_matrix < 0.05)$Letters
cld_df <- data.frame(
  Group = names(cld_letters),
  CLD = cld_letters,
  stringsAsFactors = FALSE
)

dunn_table_with_cld <- dunn_table %>%
  left_join(cld_df, by = c("Group1" = "Group")) %>%
  rename(Group1_CLD = CLD) %>%
  left_join(cld_df, by = c("Group2" = "Group")) %>%
  rename(Group2_CLD = CLD)

head(dunn_table_with_cld)
#write.csv(dunn_table_with_cld, "/Users/cmantegna/Documents/Github/WDFWmussels/output/dunn_ci3_ra.csv", row.names = FALSE) # write it out

```

## ibr_bio - site & reporting area
```{r}

# site is not significant
dunn_result <- dunnTest(ibr_bio ~ site_name, data = sample_data, method = "bh") 
dunn_df <- dunn_result$res %>%
  dplyr::select(Comparison, Z, P.unadj, P.adj) %>%
  tidyr::separate(Comparison, into = c("Group1", "Group2"), sep = " - ") %>%
  dplyr::mutate(Significant = ifelse(P.adj < 0.05, "Yes", "No"))

dunn_table <- dunn_df %>%
  dplyr::mutate(across(c(P.unadj, P.adj), round, digits = 4)) %>%
  dplyr::arrange(P.adj)
print(dunn_table) # view

# reporting area is significant
dunn_result <- dunnTest(ibr_bio ~ reporting_area, data = sample_data, method = "bh") 
dunn_df <- dunn_result$res %>%
  dplyr::select(Comparison, Z, P.unadj, P.adj) %>%
  tidyr::separate(Comparison, into = c("Group1", "Group2"), sep = " - ") %>%
  dplyr::mutate(Significant = ifelse(P.adj < 0.05, "Yes", "No"))
dunn_table <- dunn_df %>%
  dplyr::mutate(across(c(P.unadj, P.adj), round, digits = 4)) %>%
  dplyr::arrange(P.adj)
print(dunn_table) # view

groups <- unique(c(dunn_df$Group1, dunn_df$Group2)) # add letters
pval_matrix <- matrix(1, nrow = length(groups), ncol = length(groups),
                      dimnames = list(groups, groups))
for (i in 1:nrow(dunn_df)) {
  g1 <- dunn_df$Group1[i]
  g2 <- dunn_df$Group2[i]
  p <- dunn_df$P.adj[i]
  pval_matrix[g1, g2] <- p
  pval_matrix[g2, g1] <- p
}

cld_letters <- multcompLetters(pval_matrix < 0.05)$Letters
cld_df <- data.frame(
  Group = names(cld_letters),
  CLD = cld_letters,
  stringsAsFactors = FALSE
)
dunn_table_with_cld <- dunn_table %>%
  left_join(cld_df, by = c("Group1" = "Group")) %>%
  rename(Group1_CLD = CLD) %>%
  left_join(cld_df, by = c("Group2" = "Group")) %>%
  rename(Group2_CLD = CLD)
head(dunn_table_with_cld)
#write.csv(dunn_table_with_cld, "/Users/cmantegna/Documents/Github/WDFWmussels/output/dunn_ibrbio_ra.csv", row.names = FALSE) # write it out

```

## ibr_morph - site & reporting area
```{r}

# site is not significant
dunn_result <- dunnTest(ibr_morph ~ site_name, data = sample_data, method = "bh") 
dunn_df <- dunn_result$res %>%
  dplyr::select(Comparison, Z, P.unadj, P.adj) %>%
  tidyr::separate(Comparison, into = c("Group1", "Group2"), sep = " - ") %>%
  dplyr::mutate(Significant = ifelse(P.adj < 0.05, "Yes", "No"))
dunn_table <- dunn_df %>%
  dplyr::mutate(across(c(P.unadj, P.adj), round, digits = 4)) %>%
  dplyr::arrange(P.adj)
print(dunn_table) # view

# reporting area is significant
dunn_result <- dunnTest(ibr_morph ~ reporting_area, data = sample_data, method = "bh") 
dunn_df <- dunn_result$res %>%
  dplyr::select(Comparison, Z, P.unadj, P.adj) %>%
  tidyr::separate(Comparison, into = c("Group1", "Group2"), sep = " - ") %>%
  dplyr::mutate(Significant = ifelse(P.adj < 0.05, "Yes", "No"))
dunn_table <- dunn_df %>%
  dplyr::mutate(across(c(P.unadj, P.adj), round, digits = 4)) %>%
  dplyr::arrange(P.adj)
print(dunn_table) # view

groups <- unique(c(dunn_df$Group1, dunn_df$Group2)) # add letters
pval_matrix <- matrix(1, nrow = length(groups), ncol = length(groups),
                      dimnames = list(groups, groups))
for (i in 1:nrow(dunn_df)) {
  g1 <- dunn_df$Group1[i]
  g2 <- dunn_df$Group2[i]
  p <- dunn_df$P.adj[i]
  pval_matrix[g1, g2] <- p
  pval_matrix[g2, g1] <- p
}
cld_letters <- multcompLetters(pval_matrix < 0.05)$Letters
cld_df <- data.frame(
  Group = names(cld_letters),
  CLD = cld_letters,
  stringsAsFactors = FALSE
)

dunn_table_with_cld <- dunn_table %>%
  left_join(cld_df, by = c("Group1" = "Group")) %>%
  rename(Group1_CLD = CLD) %>%
  left_join(cld_df, by = c("Group2" = "Group")) %>%
  rename(Group2_CLD = CLD)

#write.csv(dunn_table_with_cld, "/Users/cmantegna/Documents/Github/WDFWmussels/output/dunn_ibrmorph_ra.csv", row.names = FALSE) # write it out

```

## ibr_combined - site & reporting area
```{r}

# site is not significant
dunn_result <- dunnTest(ibr_combined ~ site_name, data = sample_data, method = "bh") 
dunn_df <- dunn_result$res %>%
  dplyr::select(Comparison, Z, P.unadj, P.adj) %>%
  tidyr::separate(Comparison, into = c("Group1", "Group2"), sep = " - ") %>%
  dplyr::mutate(Significant = ifelse(P.adj < 0.05, "Yes", "No"))
dunn_table <- dunn_df %>%
  dplyr::mutate(across(c(P.unadj, P.adj), round, digits = 4)) %>%
  dplyr::arrange(P.adj)
print(dunn_table) # view


# reporting area is significant
dunn_result <- dunnTest(ibr_combined ~ reporting_area, data = sample_data, method = "bh") 
dunn_df <- dunn_result$res %>%
  dplyr::select(Comparison, Z, P.unadj, P.adj) %>%
  tidyr::separate(Comparison, into = c("Group1", "Group2"), sep = " - ") %>%
  dplyr::mutate(Significant = ifelse(P.adj < 0.05, "Yes", "No"))
dunn_table <- dunn_df %>%
  dplyr::mutate(across(c(P.unadj, P.adj), round, digits = 4)) %>%
  dplyr::arrange(P.adj)
print(dunn_table) # view

groups <- unique(c(dunn_df$Group1, dunn_df$Group2)) # add letters
pval_matrix <- matrix(1, nrow = length(groups), ncol = length(groups),
                      dimnames = list(groups, groups))
for (i in 1:nrow(dunn_df)) {
  g1 <- dunn_df$Group1[i]
  g2 <- dunn_df$Group2[i]
  p <- dunn_df$P.adj[i]
  pval_matrix[g1, g2] <- p
  pval_matrix[g2, g1] <- p
}

cld_letters <- multcompLetters(pval_matrix < 0.05)$Letters
cld_df <- data.frame(
  Group = names(cld_letters),
  CLD = cld_letters,
  stringsAsFactors = FALSE
)
dunn_table_with_cld <- dunn_table %>%
  left_join(cld_df, by = c("Group1" = "Group")) %>%
  rename(Group1_CLD = CLD) %>%
  left_join(cld_df, by = c("Group2" = "Group")) %>%
  rename(Group2_CLD = CLD)

#write.csv(dunn_table_with_cld, "/Users/cmantegna/Documents/Github/WDFWmussels/output/dunn_ibrcombined_ra.csv", row.names = FALSE) # write it out

```

