---
title: "initial visualization of biomarker data"
authors: Chris M
date: February 20, 2024
---

#load packages
```{r}

library(tidyverse)
library(ggplot2)
library(vegan)

```

#load data
#biomarkersbysite= p450 and SOD by site
#morphometrics= weight, length, height, and width measurements
#shellthickness= shell thickness measurements
```{r}
data<- read.csv("data/biomarkerswithsites.csv", header= TRUE, sep=",")
morph<- read.csv("data/morphometrics.csv", header= TRUE, sep=",")
thick<- read.csv("data/shellthickness.csv", header= TRUE, sep=",")

```

#inspect data
```{r}
summary(data()

```

#quick stats
```{r}
#condition factor (weight/ length)
# mean/ median/ weight, length, thickness

```

#plot SOD by site
```{r}

```

#plot p450 by site
#one site at a time and the loop for it
```{r}
#individual
# Filtering the data for site 21 
site21_df <- df[df$site_number == 21, ]

ggplot(site21_df, aes(x = factor(sample), y = p450)) +
  geom_bar(stat = "identity") +
  labs(x = "Individual Sample", y = "p450 Value") +
  ggtitle("p450 Values for Site 21 by Individual Sample")


#loop
for (site in 1:77) {
  # Filter the data for the current site
  site_df <- df[df$site_number == site, ]
  
  # Plot the bar chart for the current site
  p <- ggplot(site_df, aes(x = factor(sample), y = p450)) +
    geom_bar(stat = "identity") +
    labs(x = "Individual Sample", y = "p450 Value") +
    ggtitle(paste("p450 Values for Site", site, "by Individual Sample"))
  
  # Print the plot
  print(p)
}

```


#map sites by category (high, medium, low)
```{r}



```







