---
title: "Merging data frames"
output:
  html_document: 
    toc: true
    toc_float:
        collapsed: false
        smooth_scroll: true
    fig_width: 20
  pdf_document: 
    fig_width: 20
    fig_height: 9
---

# Directory and doc rules

```{r, setup, eval=TRUE, include=TRUE}

knitr::opts_chunk$set(
  echo = TRUE,         # Display code chunks
  eval = TRUE,         # Evaluate code chunks
  warning = FALSE,     # Hide warnings
  message = FALSE,     # Hide messages
  fig.width = 20,       # Set plot width in inches
  fig.height = 9,      # Set plot height in inches
  fig.align = "center" # Align plots to the center
)

```

# Load packages

```{r}
library(tidyr)
library(tidyverse)
library(vegan)

```

# Load data

```{r}

#getwd()
pdata<- read.csv("/Users/cmantegna/Documents/WDFWmussels/data/p450data.csv")
sdata<- read.csv("/Users/cmantegna/Documents/WDFWmussels/data/soddata.csv")
metal<- read.csv("/Users/cmantegna/Documents/WDFWmussels/data/metals.csv")

```

# Pivot data table
```{r}
df_wide <- metal %>%
  pivot_wider(names_from = analyte, values_from = dryvalue)

# Print the reshaped data frame
print(df_wide)
write.csv(df_wide, "/Users/cmantegna/Documents/WDFWmussels/data/metal_wide.csv", row.names = FALSE)
```

# Merge 
```{r}
#p450
merged_df <- merge(pdata, df_wide, by = "site_name", all = TRUE)

# Print the merged data frame
print(merged_df)
#write.csv(merged_df, "/Users/cmantegna/Documents/WDFWmussels/data/p450_analytes.csv", row.names = FALSE)
```

```{r}
#sod
merged_df2 <- merge(sdata, df_wide, by = "site_name", all = TRUE)

# Print the merged data frame
print(merged_df2)
#write.csv(merged_df2, "/Users/cmantegna/Documents/WDFWmussels/data/sod_analytes.csv", row.names = FALSE)

```

