---
title: "071- PCA and PERMANOVA"
output:
  html_document: 
    toc: true
    toc_float:
        collapsed: false
        smooth_scroll: true
    fig_width: 20
  pdf_document: 
    fig_width: 20
    fig_height: 9
---

# Directory and doc rules

```{r, setup, eval=TRUE, include=TRUE}

knitr::opts_chunk$set(
  echo = TRUE,         # Display code chunks
  eval = TRUE,         # Evaluate code chunks
  warning = FALSE,     # Hide warnings
  message = FALSE,     # Hide messages
  fig.width = 20,       # Set plot width in inches
  fig.height = 9,      # Set plot height in inches
  fig.align = "center" # Align plots to the center
)

```

# Load data
```{r}

summed<- read.csv("/Users/cmantegna/Documents/WDFWmussels/data/avg_all_summed.csv")
pcb<- read.csv("/Users/cmantegna/Documents/WDFWmussels/data/avg_all_pcb.csv")
pbde<- read.csv("/Users/cmantegna/Documents/WDFWmussels/data/avg_all_pbde.csv")
metal<- read.csv("/Users/cmantegna/Documents/WDFWmussels/data/avg_all_metal.csv")
lmw<- read.csv("/Users/cmantegna/Documents/WDFWmussels/data/avg_all_lmw.csv")
hmw<- read.csv("/Users/cmantegna/Documents/WDFWmussels/data/avg_all_hmw.csv")
ddt<- read.csv("/Users/cmantegna/Documents/WDFWmussels/data/avg_all_ddtPesticide.csv")
hch<- read.csv("/Users/cmantegna/Documents/WDFWmussels/data/avg_all_chlordanesHch.csv")

```

# permanova
```{r}

library(vegan)
# Calculate Bray-Curtis distance matrix
analytes_data <- summed[, c("sum40CB", "sumBDE", "sumCHLD", "sumDDT", "sumHCH", "sumPCB", "hmwPAH", "lmwPAH", "sumPAH", "sum16PAH", "sum42PAH")]
distance_matrix <- vegdist(analytes_data, method = "bray")

# Run PERMANOVA with reporting_area as the grouping factor
result <- adonis(distance_matrix ~ reporting_area, data = summed, permutations = 999)
print(result)


```

# CCA
```{r}

# Assuming 'data' is your full dataset, create separate data frames for responses and explanatory variables
analytes_data <- summed[, c("sum40CB", "sumBDE", "sumCHLD", "sumDDT", 
                          "sumHCH", "sumPCB", "hmwPAH", "lmwPAH", 
                          "sumPAH", "sum16PAH", "sum42PAH")]

explanatory_data <- summed[, c("avg_p450", "avg_sod", "latitude", "longitude")]

# Run the CCA
cca_model <- cca(analytes_data ~ avg_p450 + avg_sod + latitude + longitude, data = explanatory_data)

# Summary of CCA model to review canonical axes and correlations
summary(cca_model)

# Plot the CCA to visualize relationships
plot(cca_model)

```


