---
title: "grouping PAH values and metals for analysis"
---

# Load data

```{r}

#getwd()
#pdata<- read.csv("/Users/cmantegna/Documents/WDFWmussels/data/p450data.csv")
asdata<- read.csv("/Users/cmantegna/Documents/WDFWmussels/data/sod_analytes.csv")



```

# Check data

```{r}
summary(asdata)

```
#PAHgroup3 - 3 classifications
```{r}

quantiles_3 <- quantile(asdata$sumPAH, probs = seq(0, 1, length.out = 4))

# Create the new column for 3 categories
asdata$PAHgroup3 <- cut(asdata$sumPAH, breaks = quantiles_3, include.lowest = TRUE, labels = FALSE)

print(quantiles_3)
#table(asdata$PAHgroup3)

```

#PAHgroup4 - 4 classifications
```{r}

quantiles_4 <- quantile(asdata$sumPAH, probs = seq(0, 1, length.out = 5))

# Create the new column for 4 categories
asdata$PAHgroup4 <- cut(asdata$sumPAH, breaks = quantiles_4, include.lowest = TRUE, labels = FALSE)

print(quantiles_4)
#table(asdata$PAHgroup4)

```

#PAHgroup5 - 5 classifications
```{r}

quantiles_5 <- quantile(asdata$sumPAH, probs = seq(0, 1, length.out = 6))

# Create the new column for 5 categories
asdata$PAHgroup5 <- cut(asdata$sumPAH, breaks = quantiles_5, include.lowest = TRUE, labels = FALSE)

print(quantiles_5)
#table(asdata$PAHgroup5)

```

#PAHgroup6 - 6 classifications
```{r}

quantiles_6 <- quantile(asdata$sumPAH, probs = seq(0, 1, length.out = 7))

# Create the new column for 6 categories
asdata$PAHgroup6 <- cut(asdata$sumPAH, breaks = quantiles_6, include.lowest = TRUE, labels = FALSE)

print(quantiles_6)
#table(asdata$PAHgroup6)

```

#PAHgroup6 - 7 classifications
```{r}

quantiles_7 <- quantile(asdata$sumPAH, probs = seq(0, 1, length.out = 8))

# Create the new column for 6 categories
asdata$PAHgroup6 <- cut(asdata$sumPAH, breaks = quantiles_6, include.lowest = TRUE, labels = FALSE)

print(quantiles_7)
#table(asdata$PAHgroup6)

```

#PAHgroup8 - 8 classifications
```{r}

quantiles_8 <- quantile(asdata$sumPAH, probs = seq(0, 1, length.out = 9))

# Create the new column for 6 categories
asdata$PAHgroup6 <- cut(asdata$sumPAH, breaks = quantiles_6, include.lowest = TRUE, labels = FALSE)

print(quantiles_8)
#table(asdata$PAHgroup6)

```
