---
title: "Pivoting & merging data frames"
output:
  html_document: 
    toc: true
    toc_float:
        collapsed: false
        smooth_scroll: true
    fig_width: 20
  pdf_document: 
    fig_width: 20
    fig_height: 9
---

# Directory and doc rules

```{r, setup, eval=TRUE, include=TRUE}

knitr::opts_chunk$set(
  echo = TRUE,         # Display code chunks
  eval = TRUE,         # Evaluate code chunks
  warning = FALSE,     # Hide warnings
  message = FALSE,     # Hide messages
  fig.width = 20,       # Set plot width in inches
  fig.height = 9,      # Set plot height in inches
  fig.align = "center" # Align plots to the center
)

```

# Load packages

```{r}
library(tidyr)
library(tidyverse)
library(vegan)

```

# Load data

```{r}

#getwd()
#pdata<- read.csv("/Users/cmantegna/Documents/WDFWmussels/data/avgP450.csv")
#sdata<- read.csv("/Users/cmantegna/Documents/WDFWmussels/data/avgSOD.csv")
morph<- read.csv("/Users/cmantegna/Documents/WDFWmussels/data/avgMORPH.csv")
idata<- read.csv("/Users/cmantegna/Documents/WDFWmussels/data/not_for_analysis/individual_wide.csv")
odata<- read.csv("/Users/cmantegna/Documents/WDFWmussels/data/not_for_analysis/othersummed_wide.csv")
mdata<- read.csv("/Users/cmantegna/Documents/WDFWmussels/data/not_for_analysis/metal_wide.csv")
```

```{r}
summary(odata)
```

```{r}
summary(idata)
```

# Pivot data table

```{r}
#individual
df_wide <- idata %>%
  pivot_wider(names_from = analyte, values_from = dryvalue)

# Print the reshaped data frame
print(df_wide)
write.csv(df_wide, "/Users/cmantegna/Documents/WDFWmussels/data/individual_wide.csv", row.names = FALSE)

#other summed
df_wide2 <- odata %>%
  pivot_wider(names_from = analyte , values_from = dryvalue )

# Print the reshaped data frame
print(df_wide2)
write.csv(df_wide2, "/Users/cmantegna/Documents/WDFWmussels/data/othersummed_wide.csv", row.names = FALSE)
```

# Merge 
## All of the data frames are merged but only the p450_analytes2 has been adjusted for analysis. all others need to be adjusted before completing the next merge step.
```{r}
#p450
merged_df <- merge(pdata, df_wide, by = "site_name", all = TRUE)

# Print the merged data frame
head(merged_df)
write.csv(merged_df, "/Users/cmantegna/Documents/WDFWmussels/data/avgP450_analytes.csv", row.names = FALSE)

#sod
merged_df <- merge(sdata, df_wide, by = "site_name", all = TRUE)

# Print the merged data frame
head(merged_df)
write.csv(merged_df, "/Users/cmantegna/Documents/WDFWmussels/data/avgSOD_analytes.csv", row.names = FALSE)

#morphometric
merged_df <- merge(morph, idata, by = "site_name", all = TRUE)

# Print the merged data frame
print(merged_df)
write.csv(merged_df, "/Users/cmantegna/Documents/WDFWmussels/data/avgMORPH_analytes.csv", row.names = FALSE)

```

```{r}
#p450
merged_df2 <- merge(pdata, df_wide2, by = "site_name", all = TRUE)

# Print the merged data frame
head(merged_df2)
write.csv(merged_df2, "/Users/cmantegna/Documents/WDFWmussels/data/avgP450_analytes2.csv", row.names = FALSE)

#sod
merged_df2 <- merge(sdata, df_wide2, by = "site_name", all = TRUE)

# Print the merged data frame
head(merged_df2)
write.csv(merged_df2, "/Users/cmantegna/Documents/WDFWmussels/data/avgSOD_analytes2.csv", row.names = FALSE)

#morphometric
merged_df2 <- merge(morph, odata, by = "site_name", all = TRUE)

# Print the merged data frame
print(merged_df2)
write.csv(merged_df2, "/Users/cmantegna/Documents/WDFWmussels/data/avgMORPH_analytes2.csv", row.names = FALSE)

```
#metal table merge
```{r}

#p450
merged_df3 <- merge(pdata, metal_wide, by = "site_name", all = TRUE)

# Print the merged data frame
head(merged_df3)
write.csv(merged_df3, "/Users/cmantegna/Documents/WDFWmussels/data/avgP450_metals.csv", row.names = FALSE)

#morph
merged_df3 <- merge(morph, mdata, by = "site_name", all = TRUE)

# Print the merged data frame
head(merged_df3)
write.csv(merged_df3, "/Users/cmantegna/Documents/WDFWmussels/data/avgMORPH_metals.csv", row.names = FALSE)

```

# averaging df
```{r}

# Calculate the averages for columns 'at' and 'cf' for each site
averaged_data <- morph %>%
  group_by(site_name) %>%
  summarise(
    avg_at = mean(at, na.rm = TRUE),
    avg_cf = mean(cf, na.rm = TRUE)
  )

# View the averaged data
print(averaged_data)

write.csv(averaged_data, "/Users/cmantegna/Documents/WDFWmussels/data/avgMORPH.csv", row.names = FALSE)

```

