---
title: "Yellow Island Power Analysis"
output:
  html_document: 
    toc: true
    toc_float:
        collapsed: false
        smooth_scroll: true
    fig_width: 20
  pdf_document: 
    fig_width: 20
    fig_height: 9
---

# Directory and doc rules

```{r, setup, eval=TRUE, include=TRUE}

knitr::opts_chunk$set(
  echo = TRUE,         # Display code chunks
  eval = TRUE,         # Evaluate code chunks
  warning = FALSE,     # Hide warnings
  message = FALSE,     # Hide messages
  fig.width = 20,       # Set plot width in inches
  fig.height = 9,      # Set plot height in inches
  fig.align = "center" # Align plots to the center
)

```

# Load packages

```{r}
library(tidyr)
library(vegan)

```

# Power- Cohen's D
```{r}
# Install and load the pwr package
install.packages("pwr")
library(pwr)

# Define the parameters
effect_size <- 0.5  # Example effect size (Cohen's d)
alpha <- 0.05       # Significance level
power <- 0.8        # Desired power

# Conduct the power analysis
sample_size <- pwr.t.test(d = effect_size, sig.level = alpha, power = power, type = "two.sample")

# Display the result
print(sample_size)

```

# Power Cohen's F
```{r}
# Example power analysis for ANOVA

# Define the parameters
effect_size_anova <- 0.25  # Example effect size (Cohen's f)
alpha <- 0.05              # Significance level
power <- 0.8               # Desired power
num_groups <- 24           # Number of groups (8 sections * 3 zones each)

# Conduct the power analysis
sample_size_anova <- pwr.anova.test(f = effect_size_anova, sig.level = alpha, power = power, k = num_groups)

# Display the result
print(sample_size_anova)

```

