---
title: "plotting prelim"
author: "Chris"
date: "12/05/2023"
output:
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# looking at values across sites

```{r}
#install.packages("ggplot2")
library(ggplot2)

```

```{r}
# import data
data = p450_by_site

# created a feceted plot
# ggplot(data, aes(x = "Sample ID", y = Value)) +
#  geom_point() +
#  facet_wrap(~ "Site ID", scales = "free_y", ncol = 1) +
#  labs(title = "Values by Site ID", x = "Sample ID", y = "Value") +
#  theme_minimal()
```



Trying a basic bar
```{r}

# Uniform color
#barplot(height=data$Value, names=data$"Sample ID", 
#        col="#69b3a2",
#        horiz=T, las=1
#        )
```

```{r}

library(dplyr)
library(ggplot2)
library(stringr)
library(readr)
library(httr)
```

```{r}
ggplot(data, aes(fill="Value", y="Value", x="Sample ID")) + 
    geom_bar(position="dodge", stat="identity") +
    scale_fill_viridis(discrete = T, option = "E") +
    ggtitle("Site Values..") +
    facet_wrap(~"Site ID") +
    theme_ipsum() +
    theme(legend.position="none") +
    xlab("")
```

```{r}

```
